# Generated by Django 4.2.7 on 2023-11-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('locker_number', models.IntegerField(default=1)),
                ('locker_combination', models.CharField(max_length=255)),
                ('good_student', models.BooleanField()),
            ],
        ),
    ]
